baseURL = "https://cybersightglobal.com/"
languageCode = "en-us"
title = "CyberSight Global : Cyber security"
theme = "navigator hugo"
summaryLength = 10
enableRobotsTXT = true
googleAnalytics = ""
enableGitInfo = false
pygmentsCodeFences = true
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"
themesDir = "themes"
publishDir = "public"

[params]
logo = "images/logo.png"

  [params.cookies]
  enable = true
  expire_days = 2

# [[Params.listeLangues]]
# code = "fr"

[[Params.listeLangues]]
code = "en"
author = "Themefisher"
description = "Services offered by CyberSightGlobal, an IT security consultancy."


[Languages.en]
weight = 2
languageCode = "en-us"
title = "CyberSight Global : Cyber Security"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false
footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"

[Languages.en.params.hero]
enable = true
heading = "We help brands grow securely"
description = "Penetration Testing |::|   Incident response |::| Web & Mobile Apps Security "
button = true
btnText = "Know More"
btnURL = "https://cybersightglobal.com/service"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"

[Languages.en.params.aboutSm]
enable = true
title = "We provide the critical oversight for your digital assets and infrastructure"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"

[Languages.en.params.blog]
enable = true
topTitle = "OUR CYBER STORY"
title = "Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

[Languages.en.params.contact]
enable = true
topTitle = "DROP US A NOTE"
title = "Contact Us."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
address = "14/05, Stockhome <br> Victori Palace , United States"
phone = "(03) 9283 2617"
fax = "+61 3827 3590"
facebook = "https://www.facebook.com/"
twitter = "https://twitter.com/"
linkedin = "https://www.linkedin.com/"
dribbble = "https://dribbble.com/"
instagram = "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude = "-0.127758"
mapMarker = "images/marker.png"

[Languages.en.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's take a look Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

[[menu.nav]]
name = "about"
url = "about"
weight = 2

[[menu.nav]]
name = "service"
url = "service"
weight = 3

[[menu.nav]]
name = "portfolio"
url = "portfolio"
weight = 4

[[menu.nav]]
name = "blog"
url = "blog"
weight = 5

[[menu.nav]]
name = "contact"
url = "contact"
weight = 6

[[menu.service]]
name = "Incident response"
url = "service"
weight = 1

[[menu.service]]
name = "consulting"
url = "service"
weight = 2

[[menu.service]]
name = "training"
url = "service"
weight = 3

[[menu.quicklink]]
name = "partners"
url = "about"
weight = 1

[[menu.quicklink]]
name = "about"
url = "about"
weight = 2

[[menu.quicklink]]
name = "faqs"
url = "about"
weight = 3

[[menu.quicklink]]
name = "badges"
url = "about"
weight = 4
